name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create draft release
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: create-iat
        with:
          app-id: ${{ secrets.RELEASE_GITHUB_APP_ID}}
          private-key: ${{ secrets.RELEASE_GITHUB_APP_KEY }}
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        id: release
        with:
          token: ${{ steps.create-iat.outputs.token }}

  rename:
    name: Rename release title
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    env:
      GH_REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          gh release edit ${{ needs.release.outputs.tag_name }} \
          --title "Release cli-kintone ${{ needs.release.outputs.tag_name }}"

  publish-release:
    name: Publish release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [release, rename]
    env:
      GH_REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: gh release edit ${{ needs.release.outputs.tag_name }} --draft=false

