name: release
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          token: ${{ steps.RELEASE_PLEASE_GITHUB_TOKEN }}
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - release-please
  #   # リリースコミットに対してのみ実行する
  #   if: ${{ needs.release-please.outputs.release_created }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - ... # Amazon S3 へのアップロードなど
